[App] New footer layout
milanbargiel/kulturgenerator pull request #236
Opened 2020-11-27 18:24 UTC by milanbargiel

Good Evening @moritzpflueger, here comes another rebrush of the footer:

- Arrows for navigational links
- Get rid of sponsor and founder explanation texts

Closes #165

2020-11-27 22:00 UTC, moritzpflueger requested changes

2020-11-27 22:04 UTC, moritzpflueger commented
Hi @milanbargiel, looks great :) nice Job. Consider my comments and Merge this 👍

2020-11-30 08:50 UTC, milanbargiel commented on app/src/components/Footer.vue
> +        <router-link :to="{name: 'impressum'}" :class="navigationElementClass"><span :class="underlinedLinkClass">Impressum + Datenschutz</span></router-link>
Yes, it is indeed lower case..

2020-11-30 08:57 UTC, milanbargiel commented on app/src/components/Footer.vue
> +        'navigation-element--white': this.$route.meta.hasWhiteFooter
In that way, all classes are computed in one function. From my perspective, separating static and dynamic classes in two places would make the code less explicit. But that's just an opinion and we can change the code if you prefer!

2020-11-30 08:58 UTC, merged